/*
 * Configuracao.java
 *
 * Created on 11 de Setembro de 2004, 21:36
 */

package gui;

import ambiente.Ambiente;
import javax.swing.*;


/**
 *
 * @author  knoppix
 */
public class Configuracao extends javax.swing.JFrame {
    
    private Ambiente ambiente;
    private GridPanel gridPanel;
    private JTextArea relatorioMemo;
    private int numSimulacoes = 1;
    /** Creates new form Configuracao */
    public Configuracao(GridPanel gp) {
        this.gridPanel = gp;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fieldQtdPoliciais = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fieldPresenca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldQtdCriminosos = new javax.swing.JTextField();
        fieldAceleracao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        fieldTempoPatrulha = new javax.swing.JTextField();

        setTitle("Configura\u00e7\u00e3o");
        setName("frameConfiguracao");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(150, 250));
        jPanel1.setPreferredSize(new java.awt.Dimension(180, 230));
        jLabel5.setText("CONFIGURA\u00c7\u00c3O");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 10, 110, 16);

        jLabel1.setText("Policiais");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 40, 60, 16);

        fieldQtdPoliciais.setColumns(3);
        fieldQtdPoliciais.setText("5");
        jPanel1.add(fieldQtdPoliciais);
        fieldQtdPoliciais.setBounds(140, 40, 30, 20);

        jLabel4.setText("Presen\u00e7a Policial");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 70, 110, 16);

        fieldPresenca.setText("1");
        jPanel1.add(fieldPresenca);
        fieldPresenca.setBounds(140, 70, 30, 20);

        jLabel2.setText("Criminosos");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 130, 90, 16);

        fieldQtdCriminosos.setText("30");
        jPanel1.add(fieldQtdCriminosos);
        fieldQtdCriminosos.setBounds(140, 130, 30, 20);

        fieldAceleracao.setText("200");
        jPanel1.add(fieldAceleracao);
        fieldAceleracao.setBounds(140, 160, 30, 20);

        jLabel3.setText("Delay (ms)");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 160, 100, 16);

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton1);
        jButton1.setBounds(65, 200, 50, 26);

        jLabel6.setText("Tempo de Patrulha");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 100, 107, 16);

        fieldTempoPatrulha.setText("20");
        fieldTempoPatrulha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTempoPatrulhaActionPerformed(evt);
            }
        });

        jPanel1.add(fieldTempoPatrulha);
        fieldTempoPatrulha.setBounds(140, 100, 30, 20);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void fieldTempoPatrulhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTempoPatrulhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTempoPatrulhaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
        	
            int qtdPoliciais = Integer.parseInt(this.fieldQtdPoliciais.getText());
            int presencaPolicial = Integer.parseInt(this.fieldPresenca.getText());
            int tempoPatrulha = Integer.parseInt(this.fieldTempoPatrulha.getText());
            int qtdCriminosos = Integer.parseInt(this.fieldQtdCriminosos.getText());
            int aceleracao = Integer.parseInt(this.fieldAceleracao.getText());
            
            ambiente.setNumeroPoliciais(qtdPoliciais);
            ambiente.setPresencaPolicial(presencaPolicial);
            ambiente.setTempoPatrulha(tempoPatrulha);
            ambiente.setNumeroCriminosos(qtdCriminosos);
            ambiente.setFatorAcelaracao(aceleracao);
            this.alimentarRelatorio();
            
            ambiente.iniciarSimulacao();
            
            //passando ao Painel info sobre os agentes criados
            gridPanel.setPoliciais(ambiente.getVetPoliciais());
            gridPanel.setCriminoso(ambiente.getCriminoso());
            
            this.hide();
           
            
        }catch(NumberFormatException nfe)
        {
            System.out.println("Entrada invalida!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void alimentarRelatorio()
    {
    	String rel =  "*********************\n";
    		   rel += "    SIMULAÇÃO " + (this.numSimulacoes++) + "\n";
    		   rel += "*********************\n";
    		   rel += "Policiais: " + ambiente.getNumeroPoliciais() +"\n";
    		   rel += "Presença: " + ambiente.getPresencaPolicial() + "\n";
    		   rel += "Tempo de Patrulha: " + ambiente.getTempoPatrulha() + "\n";
    		   rel += "Criminosos: " + ambiente.getNumeroCriminosos() + "\n\n";
    		   
    	//relatorioMemo.setFont(new Font("Arial",Font.BOLD,12));	   
    	this.relatorioMemo.append(rel);
    	//this.relatorioMemo.
    	
    }
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        //System.exit(0);
        
    }//GEN-LAST:event_exitForm

    /**
     * Getter for property ambiente.
     * @return Value of property ambiente.
     */
    public ambiente.Ambiente getAmbiente() {
        return ambiente;
    }    
    
    /**
     * Setter for property ambiente.
     * @param ambiente New value of property ambiente.
     */
    public void setAmbiente(ambiente.Ambiente ambiente) {
        this.ambiente = ambiente;
    }
    
    /**
     * Setter for property ambiente.
     * @param ambiente New value of property ambiente.
     */
    public void setRelatorioMemo(JTextArea relatorio) {
        this.relatorioMemo = relatorio;
    }
        
  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldAceleracao;
    private javax.swing.JTextField fieldPresenca;
    private javax.swing.JTextField fieldQtdCriminosos;
    private javax.swing.JTextField fieldQtdPoliciais;
    private javax.swing.JTextField fieldTempoPatrulha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
