PROGRAM RAIZ;
USES WINCRT;
VAR
  X:INTEGER;
  
BEGIN
   WRITELN('DIGITE UM NUMERO');
   READLN(X);
   IF (X  MOD 2 = 0) THEN
   BEGIN
      WRITELN('O NUMERO E PAR E SEU QUADRADO E: ',SQR(X));
   END
   ELSE
   BEGIN
      WRITELN('O NUMERO E IMPAR E SUA RAIZ QUADRADA E:',SQRT(X):3:2);
   END;
END.
